[project]
name = "badgerr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TheWhale01", email = "ard.rasp01@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "pillow>=12.2.0",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "requests>=2.33.1",
    "typing-extensions>=4.15.0",
]

[project.scripts]
badgerr = "badgerr.main:main"

[build-system]
requires = ["uv_build>=0.9.30,<0.10.0"]
build-backend = "uv_build"
